os: linux
dist: trusty
sudo: false
cache:
  ccache: true
group: stable
addons:
  apt:
    packages:
      - cmake
      - g++-6
    sources:
      - ubuntu-toolchain-r-test
  sonarcloud:
    organization: jarvisfriends
env:
  - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
before_install:
  - eval "${MATRIX_EVAL}"
script:
  - mkdir -p build && cd build
  - cmake ..
  - make
  - cd ..
  - mkdir -p build_sonar_scanner && cd build_sonar_scanner
  - cmake ..
  - build-wrapper-linux-x86-64 --out-dir ../bw-output/ 'make'
  - cd ..
  - sonar-scanner
language: c++
