os: linux
dist: trusty
sudo: false
cache:
  ccache: true
group: stable
addons:
  apt:
    packages:
      - cmake
  sonarcloud:
    organization: jarvisfriends
script:
  - mkdir -p build && cd build
  - cmake ..
  - make
  - cd ..
  - mkdir -p build_sonar_scanner && cd build_sonar_scanner
  - cmake ..
  - build-wrapper-linux-x86-64 --out-dir ../bw-output/ 'make'
  - cd ..
  - sonar-scanner
language: c++
