os: linux
dist: xenial
sudo: true
git:
  submodules: true
cache:
  ccache: true
group: stable
addons:
  apt:
    packages:
      - cmake
      - ninja-build
      - g++-6
      - gcovr
      - python3-pexpect
    sources:
      - ubuntu-toolchain-r-test
  codecov: true
  sonarcloud:
    organization: jarvisfriends
env:
  - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
  - eval "${MATRIX_EVAL}"
script:
  - mkdir -p build && cd build
  - cmake -GNinja ..
  - ninja
  - cd .. && env SKIP=8bit_encoding ./tests.py
  - mkdir -p build_sonar_scanner && cd build_sonar_scanner
  - cmake -GNinja -DCMAKE_BUILD_TYPE=Debug ..
  - build-wrapper-linux-x86-64 --out-dir ../bw-output/ ninja replxx_coverage
  - ninja replxx_coverage
  - cd ..
  - sonar-scanner
after_success:
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
language: cpp
