version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: x64
build:
  parallel: true
  verbosity: minimal
build_script:
  - md build
  - cd %APPVEYOR_BUILD_FOLDER%\build
  - cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build . --config Release
